spring.application.name=BaiTap09_SpringSecurity6

server.port=8090
spring.thymeleaf.cache=false
spring.web.locale=vi_VN

spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1433;encrypt=false;trustServerCertificate=true;databaseName=LTW_BT09
spring.datasource.username=sa
spring.datasource.password=1

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto=update

storage.location=E:/upload

spring.security.user.name=trung
spring.security.user.password=123
