# Project Info
# ==============================
spring.application.name=BaiTap09_Json_web_token
server.port=8090

# ==============================
# Database Configuration (SQL Server)
# ==============================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=LTW_BT09_JWT;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=1
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ==============================
# JPA / Hibernate
# ==============================
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ==============================
# JWT Configuration
# ==============================
security.jwt.secret-key=BaiTap09_LTW2025_SecretKey!@#123
security.jwt.expiration-time=3600000   
# 1 hour (ms)

# ==============================
# Logging
# ==============================
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


# ==============================
storage.location=E:/upload