spring.application.name=BaiTap05

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=LTW_BT05;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=1

spring.messages.basename=i18n/messages

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto=update

# Cấu hình thư mục lưu trữ file
storage.location=E:/upload

server.port=8090
debug=false
