spring.application.name=KiemTraLTW
server.port=8080

spring.web.locale=vi_VN 

spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1433;encrypt=false;trustServerCertificate=true;databaseName=KiemTraLTW
spring.datasource.username=sa
spring.datasource.password=1

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto=update

storage.location=E:/upload

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
spring.mvc.static-path-pattern=/**