spring.application.name=BaiTap10
server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=LTW_BT09;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=1
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
